// Code generated by Wire. DO NOT EDIT.

//go:generate go run -mod=mod github.com/google/wire/cmd/wire
//go:build !wireinject
// +build !wireinject

package wire

import (
	"bit-image/internal/s3"
	"bit-image/pkg/services"
)

// Injectors from wire_app.go:

// WireApp creates the ImageService and any other dependencies required for your application
func WireApp() (*services.ImageService, error) {
	client, err := s3.NewS3Client()
	if err != nil {
		return nil, err
	}
	s3FileSystem := s3.NewS3FileSystem(client)
	handler := s3.NewHandler(s3FileSystem)
	imageService := services.NewImageService(handler)
	return imageService, nil
}
